name: Baby steps
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

# Controls when the action will run. 
on:
  push:
    branches:
      - 'feature/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  print_curr_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Print event information
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Print branch information
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Perform git diff
        run: |
          git fetch origin main
          git diff --name-only origin/main ${{ github.sha }}

      - name: Print job status
        run: echo "ğŸ This job's status is ${{ job.status }}."
      
